### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by stes** [locuslab/tta_conjugate#1]
Hi all, thanks for the great work and nice codebase!

I wanted to note that right now a LICENSE is missing, with some implications [on how others are allowed to use the code](https://choosealicense.com/no-permission/).

Could you clarify if this is intended, or whether you actually want to open source the work (under MIT, Apache 2, etc?). If that's the case I am also happy to open a PR!

**Comment by Eric-mingjie** [comment]
Hi, thanks for the kind reminder. We have just added a LICENSE to the code (MIT License).

**Comment by stes** [comment]
Great, thanks @Eric-mingjie !
